version: '3'

services:
  db:
    build:
      context: ./MySQL_sample-main/mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    networks:
      - mynetwork
    # volumes:
    #   - mysql-data:/var/lib/mysql

  llm:
    build:
      context: ./JSCopilot_LLM-main
      dockerfile: Dockerfile
    container_name: myllm
    restart: always
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

# volumes:
#   mysql-data:
